In [5]:
import pandas as pd
import statsmodels.formula.api as smf # OLS

In [24]:
df = pd.read_excel("D:\\teaching\\New Media Analysis and User Experience\\wci\\地级市党报.xlsx")

# 探索数据

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 294 entries, 0 to 293
Data columns (total 24 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   city        294 non-null    object
 1   查询网址        294 non-null    object
 2   百度百科url     294 non-null    object
 3   党报          294 non-null    object
 4   是否已经收录      74 non-null     object
 5   公号名称        24 non-null     object
 6   capital     294 non-null    object
 7   province    294 non-null    object
 8   region      294 non-null    object
 9   wci         211 non-null    float64
 10  prov_mwci   294 non-null    float64
 11  cap_wci     286 non-null    float64
 12  population  282 non-null    object
 13  density     281 non-null    float64
 14  gdp         259 non-null    float64
 15  pcgdp       281 non-null    float64
 16  income      281 non-null    object
 17  area        281 non-null    float64
 18  int_pop     280 non-null    float64
 19  int_rate    278 non-null    float64
 20  设立时间        294 non-null    object
 21  设立方式        294 non-null    object
 22  相关批文        209 non-null    object
 23  备注          225 non-null    object
dtypes: float64(9), object(15)
memory usage: 55.2+ KB

In [27]:
df.head(2)

,city,查询网址,百度百科url,党报,是否已经收录,公号名称,capital,province,region,wci,...,gdp,pcgdp,income,area,int_pop,int_rate,设立时间,设立方式,相关批文,备注
0,三沙,http://www.gsdata.cn/query/wx?q=三沙日报,https://baike.baidu.com/item/三沙日报,三沙日报,no,NaN,否,海南省,中部,NaN,...,NaN,NaN,NaN,13.0,0.0,NaN,2012年6月21日,由西沙群岛、南沙群岛、中沙群岛办事处改设,NaN,不设市辖区
1,海东,http://www.gsdata.cn/query/wx?q=海东日报,https://baike.baidu.com/item/海东日报,海东日报,no,NaN,否,青海省,西部,NaN,...,NaN,26531.0,2534292,13161.0,6.0,0.035246,2013年2月8日,由海东地区改设,国函〔2013〕23号,NaN

# 描述性分析

## WCI前10位

In [29]:
df.sort_values("wci", ascending = False)[["city","党报","wci"]].head(10)

    city     党报      wci
265   广州   广州日报  1329.72
261   杭州   杭州日报  1201.03
61    湛江   湛江日报  1124.80
270   武汉   长江日报  1072.76
243   青岛   青岛日报  1068.40
216   西宁   西宁晚报  1044.88
272   厦门   厦门日报   972.98
230   长沙   长沙晚报   971.78
241   福州   福州日报   953.87
169  哈尔滨  哈尔滨日报   936.50

## 总排名增幅最快前10位

In [19]:
df.sort_values("总排名变化", ascending = False)[["城市","公众号","WCI","总排名变化"]].head(10)

       城市        公众号     WCI    总排名变化
134    乌海       乌海日报  501.61  93315.0
111    池州       池州日报  738.58  49072.0
196    盘锦      盘锦日报社  432.85  37289.0
40     鄂州       鄂州日报  231.15  34890.0
80     咸阳       咸阳日报  512.18  32517.0
82     朔州       朔州日报  380.42  32397.0
64   巴彦淖尔  巴彦淖尔日报蒙文版  544.40  29144.0
39     赤峰       赤峰日报  378.07  25352.0
213    永州       永州日报  360.02  22902.0
174    丽水       丽水日报  603.23  22805.0

# 相关分析

In [31]:
df[["wci","gdp","population","density","income","area","int_rate"]].corr()

               wci       gdp   density      area  int_rate
wci       1.000000  0.425755  0.255766 -0.106164  0.247672
gdp       0.425755  1.000000  0.474881 -0.082336  0.525850
density   0.255766  0.474881  1.000000 -0.383889  0.350856
area     -0.106164 -0.082336 -0.383889  1.000000 -0.164533
int_rate  0.247672  0.525850  0.350856 -0.164533  1.000000

# 回归分析

In [6]:
model = smf.ols("WCI ~ 文章总数 + 发布次数", data = df).fit()

model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    WCI   R-squared:                       0.326
Model:                            OLS   Adj. R-squared:                  0.320
Method:                 Least Squares   F-statistic:                     52.23
Date:                Wed, 04 Nov 2020   Prob (F-statistic):           3.14e-19
Time:                        17:28:26   Log-Likelihood:                -1438.7
No. Observations:                 219   AIC:                             2883.
Df Residuals:                     216   BIC:                             2894.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    311.1284     30.576     10.176      0.000     250.863     371.394
文章总数           0.3130      0.241      1.296      0.196      -0.163       0.789
发布次数           5.9696      0.918      6.501      0.000       4.160       7.780
==============================================================================
Omnibus:                        7.863   Durbin-Watson:                   1.806
Prob(Omnibus):                  0.020   Jarque-Bera (JB):                8.105
Skew:                           0.471   Prob(JB):                       0.0174
Kurtosis:                       2.951   Cond. No.                         447.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""